### ISSUE TITLE
arc42 Image: outdated graphviz/dot

### ISSUE THREAD

**Issue by DG0lden** [adorsys/dockerhub-pipeline-images#44]
CentOS 7 contains graphviz 2.30.
This version has problems with layouts in PlantUML diagrams.
We need to have graphviz 2.40.1.
Unfortunately, there is no official build of it for CentOS.
First tries to do it by hands (configure, make, make install) didn't succeed. It builds, but PlantUML doesn't see it.
As a solution, we can switch for example to Ubuntu or Fedora image instead of CentOS: https://graphviz.gitlab.io/download/

**Comment by jkroepke** [comment]
> This version has problems with layouts in PlantUML diagrams.
> We need to have graphviz 2.40.1

Are you sure? http://plantuml.com/de/faq

> Which version of Graphviz should I use ?
> [...]
> Note that versions 2.39 and 2.40 do not work very well with PlantUML.


It's looks like using Graphviz 2.38 would be the best?

**Comment by DG0lden** [comment]
It was everything ok before the last update of the image. Now images generated locally (with 2.40.1) and with the image are differ and drastically worse than on local version.
